import { createContext, useContext, useState, useEffect } from 'react';

const DataContext = createContext();

export function useData() {
  return useContext(DataContext);
}

// Enhanced Product Catalog - Premium Fashion Store
const initialProducts = [
  // EVENING WEAR
  { 
    id: 1, 
    name: 'Silk Evening Gown', 
    price: 2499, 
    image: '/img/evening dress.avif', 
    category: 'Evening', 
    subcategory: 'Gowns',
    designer: 'Maison Élite',
    material: 'Italian Silk',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Midnight Blue'],
    description: 'Timeless elegance meets modern sophistication in this floor-length silk gown.',
    rating: 5, 
    stock: 5, 
    sales: 12, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },
  { 
    id: 2, 
    name: 'Velvet Gala Dress', 
    price: 3200, 
    image: '/img/evening3.avif', 
    category: 'Evening', 
    subcategory: 'Gowns',
    designer: 'Maison Élite',
    material: 'French Velvet',
    sizes: ['S', 'M', 'L'],
    colors: ['Burgundy', 'Emerald'],
    description: 'Luxurious velvet gown perfect for gala events and red carpet moments.',
    rating: 5, 
    stock: 3, 
    sales: 8, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },
  { 
    id: 3, 
    name: 'Sequin Cocktail Dress', 
    price: 1200, 
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=400', 
    category: 'Evening', 
    subcategory: 'Cocktail',
    designer: 'Maison Élite',
    material: 'Sequined Fabric',
    sizes: ['XS', 'S', 'M'],
    colors: ['Gold', 'Silver', 'Rose Gold'],
    description: 'Dazzling sequin cocktail dress that catches every light.',
    rating: 4, 
    stock: 8, 
    sales: 18, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  { 
    id: 4, 
    name: 'Embroidered Evening Gown', 
    price: 6500, 
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&q=80&w=400', 
    category: 'Evening', 
    subcategory: 'Gowns',
    designer: 'Maison Élite Couture',
    material: 'Hand-Embroidered Silk',
    sizes: ['S', 'M', 'L'],
    colors: ['Champagne', 'Blush'],
    description: 'Exquisite hand-embroidered gown featuring intricate beadwork.',
    rating: 5, 
    stock: 2, 
    sales: 6, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },

  // READY-TO-WEAR
  { 
    id: 5, 
    name: 'Tailored Power Blazer', 
    price: 899, 
    image: '/img/Tailored Power Suit.avif', 
    category: 'Ready-to-Wear', 
    subcategory: 'Blazers',
    designer: 'Maison Élite',
    material: 'Wool Blend',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Charcoal'],
    description: 'Perfectly tailored blazer for the modern professional.',
    rating: 4, 
    stock: 15, 
    sales: 45, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: true,
    originalPrice: 1099
  },
  { 
    id: 6, 
    name: 'Wool Trench Coat', 
    price: 1450, 
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Coats',
    designer: 'Maison Élite',
    material: 'Merino Wool',
    sizes: ['S', 'M', 'L'],
    colors: ['Camel', 'Black'],
    description: 'Classic trench coat crafted from premium merino wool.',
    rating: 5, 
    stock: 7, 
    sales: 22, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },
  { 
    id: 7, 
    name: 'Satin Blouse', 
    price: 320, 
    image: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Tops',
    designer: 'Maison Élite',
    material: 'Silk Satin',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Black', 'Dusty Rose'],
    description: 'Luxurious satin blouse with French seams.',
    rating: 4, 
    stock: 25, 
    sales: 55, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 8, 
    name: 'Linen Summer Dress', 
    price: 580, 
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Dresses',
    designer: 'Maison Élite',
    material: 'European Linen',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Beige', 'Sky Blue'],
    description: 'Breezy linen dress perfect for summer elegance.',
    rating: 4, 
    stock: 18, 
    sales: 38, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  { 
    id: 9, 
    name: 'Cashmere Turtleneck', 
    price: 450, 
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Knitwear',
    designer: 'Maison Élite',
    material: '100% Cashmere',
    sizes: ['S', 'M', 'L'],
    colors: ['Cream', 'Charcoal', 'Navy'],
    description: 'Luxuriously soft cashmere turtleneck.',
    rating: 5, 
    stock: 12, 
    sales: 28, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 10, 
    name: 'Wide-Leg Trousers', 
    price: 520, 
    image: 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Pants',
    designer: 'Maison Élite',
    material: 'Wool Crepe',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Ivory'],
    description: 'Elegant wide-leg trousers with flattering silhouette.',
    rating: 5, 
    stock: 20, 
    sales: 42, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },

  // BRIDAL
  { 
    id: 11, 
    name: 'Lace Bridal Veil', 
    price: 450, 
    image: '/img/ethereal.avif', 
    category: 'Bridal', 
    subcategory: 'Accessories',
    designer: 'Maison Élite Bridal',
    material: 'French Lace',
    sizes: ['One Size'],
    colors: ['Ivory', 'White'],
    description: 'Delicate lace veil with intricate detailing.',
    rating: 5, 
    stock: 8, 
    sales: 23, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 12, 
    name: 'Custom Wedding Dress', 
    price: 8500, 
    image: 'https://images.unsplash.com/photo-1594552072238-b8a33785b261?auto=format&fit=crop&q=80&w=400', 
    category: 'Bridal', 
    subcategory: 'Gowns',
    designer: 'Maison Élite Couture',
    material: 'Silk Mikado',
    sizes: ['Custom Made'],
    colors: ['Ivory', 'White', 'Blush'],
    description: 'Bespoke wedding gown tailored to perfection.',
    rating: 5, 
    stock: 1, 
    sales: 3, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },
  { 
    id: 13, 
    name: 'Bridal Corset', 
    price: 1800, 
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=400', 
    category: 'Bridal', 
    subcategory: 'Bodices',
    designer: 'Maison Élite Bridal',
    material: 'Structured Satin',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory', 'White'],
    description: 'Perfectly structured bridal corset for elegant support.',
    rating: 5, 
    stock: 5, 
    sales: 14, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 14, 
    name: 'Bridal Shoes - Satin Pumps', 
    price: 550, 
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=400', 
    category: 'Bridal', 
    subcategory: 'Shoes',
    designer: 'Maison Élite',
    material: 'Satin',
    sizes: ['35', '36', '37', '38', '39', '40'],
    colors: ['Ivory', 'White', 'Champagne'],
    description: 'Elegant satin pumps for your special day.',
    rating: 5, 
    stock: 4, 
    sales: 11, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },

  // ACCESSORIES
  { 
    id: 15, 
    name: 'Chiffon Evening Scarf', 
    price: 120, 
    image: '/img/taquilla.avif', 
    category: 'Accessories', 
    subcategory: 'Scarves',
    designer: 'Maison Élite',
    material: 'Silk Chiffon',
    sizes: ['One Size'],
    colors: ['Black', 'Ivory', 'Champagne'],
    description: 'Lightweight chiffon scarf with elegant drape.',
    rating: 4, 
    stock: 50, 
    sales: 120, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 16, 
    name: 'Diamond Tiara', 
    price: 4500, 
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Jewelry',
    designer: 'Maison Élite Jewelry',
    material: 'White Gold & Diamonds',
    sizes: ['One Size'],
    colors: ['White Gold'],
    description: 'Exquisite diamond tiara fit for royalty.',
    rating: 5, 
    stock: 2, 
    sales: 5, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },
  { 
    id: 17, 
    name: 'Cashmere Wrap', 
    price: 680, 
    image: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Wraps',
    designer: 'Maison Élite',
    material: '100% Cashmere',
    sizes: ['One Size'],
    colors: ['Camel', 'Grey', 'Black'],
    description: 'Luxurious cashmere wrap for any occasion.',
    rating: 4, 
    stock: 20, 
    sales: 35, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 18, 
    name: 'Beaded Evening Clutch', 
    price: 350, 
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Bags',
    designer: 'Maison Élite',
    material: 'Beaded Satin',
    sizes: ['One Size'],
    colors: ['Gold', 'Silver', 'Black'],
    description: 'Hand-beaded clutch perfect for evening events.',
    rating: 5, 
    stock: 12, 
    sales: 28, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 19, 
    name: 'Leather Tote Bag', 
    price: 950, 
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Bags',
    designer: 'Maison Élite',
    material: 'Italian Leather',
    sizes: ['One Size'],
    colors: ['Black', 'Cognac', 'Navy'],
    description: 'Spacious leather tote crafted from finest Italian leather.',
    rating: 5, 
    stock: 10, 
    sales: 42, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  { 
    id: 20, 
    name: 'Pearl Necklace Set', 
    price: 780, 
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Jewelry',
    designer: 'Maison Élite Jewelry',
    material: 'Freshwater Pearls',
    sizes: ['One Size'],
    colors: ['White', 'Champagne'],
    description: 'Elegant freshwater pearl necklace and earring set.',
    rating: 5, 
    stock: 6, 
    sales: 15, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 21, 
    name: 'Silk Pocket Square', 
    price: 85, 
    image: 'https://images.unsplash.com/photo-1592878904946-b3cd8ae243d0?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Scarves',
    designer: 'Maison Élite',
    material: 'Pure Silk',
    sizes: ['One Size'],
    colors: ['Navy', 'Burgundy', 'Forest Green'],
    description: 'Sophisticated silk pocket square for formal wear.',
    rating: 4, 
    stock: 40, 
    sales: 95, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 22, 
    name: 'Crystal Drop Earrings', 
    price: 420, 
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Jewelry',
    designer: 'Maison Élite Jewelry',
    material: 'Sterling Silver & Crystals',
    sizes: ['One Size'],
    colors: ['Silver'],
    description: 'Stunning crystal drop earrings that catch the light.',
    rating: 5, 
    stock: 15, 
    sales: 32, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 23, 
    name: 'Vintage Brooch Set', 
    price: 650, 
    image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Jewelry',
    designer: 'Maison Élite Heritage',
    material: 'Gold-Plated Metal',
    sizes: ['One Size'],
    colors: ['Gold'],
    description: 'Vintage-inspired brooch set with timeless appeal.',
    rating: 5, 
    stock: 8, 
    sales: 21, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },

  // CUSTOM/BESPOKE
  { 
    id: 24, 
    name: 'Bespoke Tailored Suit', 
    price: 5200, 
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=400', 
    category: 'Custom', 
    subcategory: 'Suits',
    designer: 'Maison Élite Bespoke',
    material: 'Super 150s Wool',
    sizes: ['Custom Made'],
    colors: ['Navy', 'Charcoal', 'Black'],
    description: 'Fully bespoke suit tailored to your exact measurements.',
    rating: 5, 
    stock: 2, 
    sales: 8, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },
  { 
    id: 25, 
    name: 'Custom Evening Cape', 
    price: 3800, 
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=400', 
    category: 'Custom', 
    subcategory: 'Outerwear',
    designer: 'Maison Élite Couture',
    material: 'Velvet & Silk',
    sizes: ['Custom Made'],
    colors: ['Midnight Blue', 'Burgundy', 'Black'],
    description: 'Dramatic custom cape for red carpet moments.',
    rating: 5, 
    stock: 1, 
    sales: 4, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 26, 
    name: 'Monogrammed Silk Robe', 
    price: 2200, 
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&q=80&w=400', 
    category: 'Custom', 
    subcategory: 'Loungewear',
    designer: 'Maison Élite',
    material: 'Pure Silk',
    sizes: ['S', 'M', 'L'],
    colors: ['Ivory', 'Navy', 'Burgundy'],
    description: 'Luxurious silk robe with personalized monogramming.',
    rating: 5, 
    stock: 3, 
    sales: 9, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },

  // NEW ARRIVALS - SPRING/SUMMER COLLECTION
  { 
    id: 27, 
    name: 'Silk Slip Dress', 
    price: 680, 
    image: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Dresses',
    designer: 'Maison Élite',
    material: 'Silk Charmeuse',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Champagne', 'Black', 'Sage'],
    description: 'Minimalist silk slip dress with delicate straps.',
    rating: 5, 
    stock: 14, 
    sales: 8, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  { 
    id: 28, 
    name: 'Leather Biker Jacket', 
    price: 1850, 
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Jackets',
    designer: 'Maison Élite',
    material: 'Lambskin Leather',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Cognac'],
    description: 'Classic biker jacket in buttery soft lambskin.',
    rating: 5, 
    stock: 9, 
    sales: 12, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  { 
    id: 29, 
    name: 'High-Waist Pencil Skirt', 
    price: 420, 
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Skirts',
    designer: 'Maison Élite',
    material: 'Wool Blend',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Burgundy'],
    description: 'Flattering high-waist pencil skirt for professional elegance.',
    rating: 4, 
    stock: 22, 
    sales: 35, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  { 
    id: 30, 
    name: 'Oversized Wool Coat', 
    price: 1680, 
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Coats',
    designer: 'Maison Élite',
    material: 'Merino Wool',
    sizes: ['S', 'M', 'L'],
    colors: ['Camel', 'Grey', 'Black'],
    description: 'Oversized silhouette in luxurious merino wool.',
    rating: 5, 
    stock: 8, 
    sales: 15, 
    visible: true,
    featured: true,
    newArrival: true,
    onSale: false
  },
  { 
    id: 31, 
    name: 'Pleated Midi Skirt', 
    price: 540, 
    image: 'https://images.unsplash.com/photo-1590735213920-68192a487bc2?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Skirts',
    designer: 'Maison Élite',
    material: 'Silk Crepe',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Blush', 'Ivory', 'Black'],
    description: 'Flowing pleated midi skirt with timeless elegance.',
    rating: 5, 
    stock: 16, 
    sales: 24, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  
  // STATEMENT PIECES
  { 
    id: 32, 
    name: 'Feather-Trimmed Jacket', 
    price: 2400, 
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea8a769f?auto=format&fit=crop&q=80&w=400', 
    category: 'Evening', 
    subcategory: 'Jackets',
    designer: 'Maison Élite Couture',
    material: 'Silk & Ostrich Feathers',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'White'],
    description: 'Dramatic feather-trimmed evening jacket.',
    rating: 5, 
    stock: 3, 
    sales: 5, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },
  { 
    id: 33, 
    name: 'Crystal-Embellished Belt', 
    price: 380, 
    image: 'https://images.unsplash.com/photo-1566206091558-7f218b696731?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Belts',
    designer: 'Maison Élite',
    material: 'Leather & Crystals',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Gold'],
    description: 'Statement belt with crystal embellishments.',
    rating: 5, 
    stock: 12, 
    sales: 18, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 34, 
    name: 'Cashmere Cardigan', 
    price: 720, 
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Knitwear',
    designer: 'Maison Élite',
    material: '100% Cashmere',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Cream', 'Grey', 'Navy'],
    description: 'Luxuriously soft cashmere cardigan.',
    rating: 5, 
    stock: 18, 
    sales: 42, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 35, 
    name: 'Silk Palazzo Pants', 
    price: 620, 
    image: 'https://images.unsplash.com/photo-1594633365224-6cf6f8b5c2e1?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Pants',
    designer: 'Maison Élite',
    material: 'Silk Crepe',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Ivory', 'Emerald'],
    description: 'Flowing palazzo pants in luxurious silk.',
    rating: 5, 
    stock: 14, 
    sales: 28, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  { 
    id: 36, 
    name: 'Woven Straw Hat', 
    price: 180, 
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Hats',
    designer: 'Maison Élite',
    material: 'Italian Straw',
    sizes: ['One Size'],
    colors: ['Natural', 'Black'],
    description: 'Wide-brimmed Italian straw hat for summer sophistication.',
    rating: 4, 
    stock: 25, 
    sales: 45, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },

  // LUXURY ACCESSORIES
  { 
    id: 37, 
    name: 'Leather Gloves', 
    price: 280, 
    image: 'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Gloves',
    designer: 'Maison Élite',
    material: 'Lambskin Leather',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Burgundy', 'Cognac'],
    description: 'Butter-soft lambskin leather gloves.',
    rating: 5, 
    stock: 30, 
    sales: 52, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 38, 
    name: 'Gold Chain Bracelet', 
    price: 520, 
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Jewelry',
    designer: 'Maison Élite Jewelry',
    material: '18K Gold Plated',
    sizes: ['One Size'],
    colors: ['Gold'],
    description: 'Chunky gold chain bracelet for modern elegance.',
    rating: 5, 
    stock: 10, 
    sales: 22, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  { 
    id: 39, 
    name: 'Sunglasses - Aviator', 
    price: 350, 
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Eyewear',
    designer: 'Maison Élite',
    material: 'Metal & UV Protection Glass',
    sizes: ['One Size'],
    colors: ['Gold/Green', 'Silver/Grey'],
    description: 'Classic aviator sunglasses with premium UV protection.',
    rating: 5, 
    stock: 28, 
    sales: 68, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 40, 
    name: 'Leather Belt - Classic', 
    price: 220, 
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583ba?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Belts',
    designer: 'Maison Élite',
    material: 'Italian Leather',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Brown', 'Cognac'],
    description: 'Timeless leather belt with brushed gold hardware.',
    rating: 5, 
    stock: 40, 
    sales: 85, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },

  // SALE ITEMS
  { 
    id: 41, 
    name: 'Knit Sweater Dress', 
    price: 380, 
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Dresses',
    designer: 'Maison Élite',
    material: 'Merino Wool',
    sizes: ['S', 'M', 'L'],
    colors: ['Grey', 'Camel', 'Black'],
    description: 'Cozy knit sweater dress for effortless style.',
    rating: 4, 
    stock: 12, 
    sales: 28, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: true,
    originalPrice: 550
  },
  { 
    id: 42, 
    name: 'Cropped Blazer', 
    price: 620, 
    image: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Blazers',
    designer: 'Maison Élite',
    material: 'Wool Blend',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Ivory', 'Camel'],
    description: 'Modern cropped blazer with structured shoulders.',
    rating: 4, 
    stock: 16, 
    sales: 32, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: true,
    originalPrice: 850
  },
  { 
    id: 43, 
    name: 'Statement Earrings Set', 
    price: 180, 
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Jewelry',
    designer: 'Maison Élite',
    material: 'Gold-Plated Metal',
    sizes: ['One Size'],
    colors: ['Gold'],
    description: 'Bold statement earrings for evening wear.',
    rating: 4, 
    stock: 20, 
    sales: 42, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: true,
    originalPrice: 280
  },
  { 
    id: 44, 
    name: 'Ankle Boots - Leather', 
    price: 480, 
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Shoes',
    designer: 'Maison Élite',
    material: 'Italian Leather',
    sizes: ['36', '37', '38', '39', '40', '41'],
    colors: ['Black', 'Brown'],
    description: 'Classic leather ankle boots with block heel.',
    rating: 5, 
    stock: 18, 
    sales: 38, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: true,
    originalPrice: 650
  },

  // PREMIUM COLLECTION
  { 
    id: 45, 
    name: 'Fur-Lined Parka', 
    price: 3200, 
    image: 'https://images.unsplash.com/photo-1539533113339-025c0921ef9b?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Coats',
    designer: 'Maison Élite Premium',
    material: 'Down & Fur',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Navy', 'Khaki'],
    description: 'Luxury parka with genuine fur lining.',
    rating: 5, 
    stock: 4, 
    sales: 9, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },
  { 
    id: 46, 
    name: 'Designer Sneakers', 
    price: 680, 
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Shoes',
    designer: 'Maison Élite',
    material: 'Leather & Suede',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43'],
    colors: ['White', 'Black', 'Grey'],
    description: 'Luxury designer sneakers in premium leather.',
    rating: 5, 
    stock: 22, 
    sales: 48, 
    visible: true,
    featured: false,
    newArrival: true,
    onSale: false
  },
  { 
    id: 47, 
    name: 'Silk Kimono Robe', 
    price: 850, 
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Loungewear',
    designer: 'Maison Élite',
    material: 'Pure Silk',
    sizes: ['S', 'M', 'L'],
    colors: ['Floral Print', 'Black', 'Ivory'],
    description: 'Elegant silk kimono robe with delicate prints.',
    rating: 5, 
    stock: 8, 
    sales: 16, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 48, 
    name: 'Cashmere Scarf', 
    price: 320, 
    image: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Scarves',
    designer: 'Maison Élite',
    material: '100% Cashmere',
    sizes: ['One Size'],
    colors: ['Camel', 'Grey', 'Navy', 'Black'],
    description: 'Ultra-soft cashmere scarf for timeless elegance.',
    rating: 5, 
    stock: 35, 
    sales: 72, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
  { 
    id: 49, 
    name: 'Structured Shoulder Bag', 
    price: 1200, 
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=400', 
    category: 'Accessories', 
    subcategory: 'Bags',
    designer: 'Maison Élite',
    material: 'Italian Leather',
    sizes: ['One Size'],
    colors: ['Black', 'Tan', 'Burgundy'],
    description: 'Structured shoulder bag in premium Italian leather.',
    rating: 5, 
    stock: 10, 
    sales: 24, 
    visible: true,
    featured: true,
    newArrival: false,
    onSale: false
  },
  { 
    id: 50, 
    name: 'Silk Pajama Set', 
    price: 580, 
    image: 'https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&q=80&w=400', 
    category: 'Ready-to-Wear', 
    subcategory: 'Loungewear',
    designer: 'Maison Élite',
    material: 'Mulberry Silk',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Navy', 'Blush'],
    description: 'Luxurious silk pajama set for elegant nights.',
    rating: 5, 
    stock: 20, 
    sales: 38, 
    visible: true,
    featured: false,
    newArrival: false,
    onSale: false
  },
];

const initialUsers = [
  { id: 1, name: 'Admin User', email: 'admin@kaito.com', role: 'admin', status: 'Active', lastLogin: '2026-02-04' },
  { id: 2, name: 'Staff Member', email: 'staff@kaito.com', role: 'staff', status: 'Active', lastLogin: '2026-02-03' },
  { id: 3, name: 'Jane Doe', email: 'client@example.com', role: 'client', status: 'Active', lastLogin: '2026-02-02' },
];

export function DataProvider({ children }) {
  // Load from local storage or use initial
  const [products, setProducts] = useState(() => {
    const saved = localStorage.getItem('products');
    if (saved) {
      const parsed = JSON.parse(saved);
      // Ensure all products have the visible property and new fields
      return parsed.map(p => ({ 
        ...p, 
        visible: p.visible !== undefined ? p.visible : true,
        featured: p.featured || false,
        newArrival: p.newArrival || false,
        onSale: p.onSale || false
      }));
    }
    return initialProducts;
  });

  const [users, setUsers] = useState(() => {
    const saved = localStorage.getItem('users');
    return saved ? JSON.parse(saved) : initialUsers;
  });

  // Persist to local storage
  useEffect(() => {
    localStorage.setItem('products', JSON.stringify(products));
  }, [products]);

  useEffect(() => {
    localStorage.setItem('users', JSON.stringify(users));
  }, [users]);

  // Product Actions
  const addProduct = (product) => {
    setProducts(prev => [...prev, { 
      ...product, 
      id: Date.now(), 
      rating: 5, 
      sales: 0, 
      visible: true,
      featured: false,
      newArrival: true,
      onSale: false
    }]);
  };

  const removeProduct = (id) => {
    setProducts(prev => prev.filter(p => p.id !== id));
  };

  const toggleProductVisibility = (id) => {
    setProducts(prev => prev.map(p => 
      p.id === id ? { ...p, visible: !p.visible } : p
    ));
  };

  const updateProduct = (id, updates) => {
    setProducts(prev => prev.map(p => 
      p.id === id ? { ...p, ...updates } : p
    ));
  };

  // User Actions
  const addUser = (user) => {
    setUsers(prev => [...prev, { ...user, id: Date.now(), status: 'Active', lastLogin: '-' }]);
  };

  const removeUser = (id) => {
    if (users.find(u => u.id === id)?.role === 'admin' && users.filter(u => u.role === 'admin').length <= 1) {
      alert("Cannot remove the last admin.");
      return;
    }
    setUsers(prev => prev.filter(u => u.id !== id));
  };

  // Get only visible products (for shop display)
  const visibleProducts = products.filter(p => p.visible);
  
  // Get featured products
  const featuredProducts = visibleProducts.filter(p => p.featured);
  
  // Get new arrivals
  const newArrivals = visibleProducts.filter(p => p.newArrival);
  
  // Get sale items
  const saleItems = visibleProducts.filter(p => p.onSale);

  return (
    <DataContext.Provider value={{
      products,
      visibleProducts,
      featuredProducts,
      newArrivals,
      saleItems,
      users,
      addProduct,
      removeProduct,
      toggleProductVisibility,
      updateProduct,
      addUser,
      removeUser
    }}>
      {children}
    </DataContext.Provider>
  );
}
